# Generated by Django 5.2.7 on 2026-05-19 21:48

import users.tenant
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_student_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', users.tenant.OrganizationScopedUserManager()),
            ],
        ),
    ]
