# Generated by Django 5.2.7 on 2026-06-03 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_default_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_source',
            field=models.CharField(blank=True, help_text='Source or publisher attribution for rights tracking.', max_length=512),
        ),
        migrations.AddField(
            model_name='book',
            name='license_type',
            field=models.CharField(choices=[('public_domain', 'Public Domain'), ('licensed', 'Licensed (permission granted)'), ('restricted', 'Restricted (do not distribute)'), ('unknown', 'Unknown — needs review')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='rights_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rights_status',
            field=models.CharField(choices=[('approved', 'Approved for distribution'), ('draft', 'Draft — not yet approved'), ('expired', 'License expired'), ('restricted', 'Restricted — internal use only'), ('unknown', 'Unknown — needs review')], default='draft', help_text="Only 'approved' books should be production-visible.", max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='analytics_consent',
            field=models.BooleanField(default=False, help_text='User opted in to optional analytics/improvement data collection.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='analytics_consent_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp when analytics consent was last changed.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp when user accepted the Privacy Policy.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_version',
            field=models.CharField(blank=True, default='', help_text='Version tag of the Privacy Policy accepted.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_managed',
            field=models.BooleanField(default=False, help_text='Account is managed by the linked school/org (Phase 2 governance).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp when user accepted the current Terms of Use.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_version',
            field=models.CharField(blank=True, default='', help_text="Version tag of the Terms accepted (e.g. '2024-06').", max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('content_publish', 'Content published'), ('content_unpublish', 'Content unpublished'), ('account_delete_request', 'Account deletion requested'), ('account_deleted', 'Account deleted'), ('consent_change', 'Consent updated'), ('policy_accept', 'Policy accepted'), ('data_export', 'Data export generated'), ('admin_action', 'Admin action')], max_length=40)),
                ('target_type', models.CharField(blank=True, help_text="Django content type label of the affected object, e.g. 'users.userprofile'.", max_length=80)),
                ('target_id', models.CharField(blank=True, help_text='String PK of the affected object.', max_length=80)),
                ('notes', models.TextField(blank=True, help_text='Human-readable event summary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed the action (null for system events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('export', 'Export my data'), ('delete', 'Delete my account'), ('correct', 'Correct my information'), ('withdraw_analytics', 'Withdraw analytics consent'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='User-provided details or admin resolution notes.')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not shown to user).')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
