# Generated by Django 5.2.7 on 2026-06-03 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_compliance_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='data_storage_region',
            field=models.CharField(blank=True, help_text="Region/country where this org's data is primarily stored (for disclosure purposes).", max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='dpa_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the school/org administrator accepted the Data Processing Agreement.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='dpa_accepted_by',
            field=models.CharField(blank=True, help_text='Name/title of person who accepted the DPA on behalf of the org.', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='governs_student_data',
            field=models.BooleanField(default=False, help_text='True = this org has accepted a DPA and governs student data processing. New student accounts registered under this org will be school_managed=True.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='privacy_contact_email',
            field=models.EmailField(blank=True, help_text='School/org DPO or privacy contact email for data requests.', max_length=254),
        ),
        migrations.CreateModel(
            name='ParentalConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_name', models.CharField(blank=True, help_text='Name of guardian (required when guardian account is not linked).', max_length=255)),
                ('guardian_email', models.EmailField(blank=True, help_text='Email address used for consent confirmation.', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending — awaiting guardian confirmation'), ('granted', 'Consent granted'), ('revoked', 'Consent revoked')], default='pending', max_length=20)),
                ('consent_method', models.CharField(choices=[('in_app', 'Parent completed in-app consent flow'), ('school', 'School provided parental consent documentation'), ('email', 'Parental consent received by email'), ('paper', 'Signed paper consent on file')], default='in_app', max_length=20)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes or reference to paper consent document.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(blank=True, help_text='The parent/guardian UserProfile, if they have an account. Null if consent was provided by a school or off-platform.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_parental_consents', to=settings.AUTH_USER_MODEL)),
                ('minor', models.ForeignKey(help_text='The under-18 student account this consent covers.', on_delete=django.db.models.deletion.CASCADE, related_name='parental_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parental Consent',
                'verbose_name_plural': 'Parental Consents',
                'ordering': ['-created_at'],
            },
        ),
    ]
