# Generated by Django 5.2.7 on 2026-06-03 05:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_school_managed_parental_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive failed login attempts since last successful login.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_failed_login_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of most recent failed login attempt.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account is temporarily locked for login until this timestamp. Null means not locked.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, help_text='When set, the account is queued for anonymization. The apply_retention_policy management command will delete/anonymize it after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('content_publish', 'Content published'), ('content_unpublish', 'Content unpublished'), ('account_delete_request', 'Account deletion requested'), ('account_deleted', 'Account deleted'), ('consent_change', 'Consent updated'), ('policy_accept', 'Policy accepted'), ('data_export', 'Data export generated'), ('data_access', 'User data accessed by admin'), ('data_delete', 'User data deleted / anonymized'), ('admin_action', 'Admin action')], max_length=40),
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('platform', 'Platform-wide default'), ('org', 'Organization-specific override')], default='platform', max_length=10)),
                ('data_category', models.CharField(choices=[('account', 'User account & profile data'), ('reading', 'Reading progress & history'), ('audit', 'Audit log entries'), ('consent', 'Consent records')], max_length=20)),
                ('retention_days', models.PositiveIntegerField(help_text='Number of days after account deletion/deactivation before data is permanently anonymized. Use 0 for immediate deletion.')),
                ('notes', models.TextField(blank=True, help_text='Legal basis / justification for this retention period.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Required when scope=org; ignored when scope=platform.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='users.organization')),
            ],
            options={
                'verbose_name': 'Retention Policy',
                'verbose_name_plural': 'Retention Policies',
                'ordering': ['scope', 'data_category'],
                'unique_together': {('scope', 'organization', 'data_category')},
            },
        ),
    ]
