# Generated by Django 5.2.7 on 2026-10-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_stripe_subscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetchallenge',
            new_name='users_passw_email_5e50b6_idx',
            old_name='users_passw_email_7c2e1a_idx',
        ),
        migrations.AddField(
            model_name='organization',
            name='join_code',
            field=models.CharField(blank=True, help_text='When set, students must enter this code to register under this school. Keeps school-only resources away from students who merely pick the school name.', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_school_admin',
            field=models.BooleanField(default=False, help_text='Staff member who can manage accounts and resources for their school.'),
        ),
        migrations.AlterField(
            model_name='parentinvite',
            name='invite_email',
            field=models.EmailField(blank=True, help_text='Optional email the invite was sent to (for validation hints).', max_length=254),
        ),
    ]
