# Generated by Django 5.2.7 on 2026-10-05 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_school_admin_join_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('bug', "Something isn't working"), ('idea', 'Feature idea'), ('content', 'Content / textbook issue'), ('question', 'Question / need help'), ('praise', 'Something I like'), ('other', 'Other')], default='other', max_length=16)),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 overall rating.', null=True)),
                ('screen', models.CharField(blank=True, help_text='Screen the user was on.', max_length=200)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('contact_ok', models.BooleanField(default=True, help_text='User is happy to be contacted.')),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Reviewed'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('done', 'Done'), ('wont_do', "Won't do")], default='new', max_length=16)),
                ('priority', models.CharField(blank=True, choices=[('', 'Not set'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='users.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
