# Generated by Django 5.2.7 on 2026-05-19 20:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IGCSEChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=96)),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='IGCSESubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='IGCSEGeneratedSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed'), ('published', 'Published')], default='pending', max_length=20)),
                ('quality_score', models.FloatField(blank=True, help_text='Optional 0..1 quality score from the pipeline.', null=True)),
                ('pipeline_bundle_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_sets', to='igcse_catalog.igcsechapter')),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='igcsechapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='igcse_catalog.igcsesubject'),
        ),
        migrations.CreateModel(
            name='PracticePaperAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, upload_to='igcse/papers/')),
                ('pdf_url', models.URLField(blank=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_paper', to='igcse_catalog.igcsegeneratedset')),
            ],
        ),
        migrations.CreateModel(
            name='SimulatorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulator_set_id', models.CharField(db_index=True, max_length=128)),
                ('public_url', models.URLField(blank=True)),
                ('artifact_file', models.FileField(blank=True, upload_to='igcse/simulators/')),
                ('artifact_url', models.URLField(blank=True)),
                ('artifact_json', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.CharField(blank=True, max_length=32)),
                ('build_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulator', to='igcse_catalog.igcsegeneratedset')),
            ],
        ),
        migrations.CreateModel(
            name='WorkedSolutionsAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, upload_to='igcse/solutions/')),
                ('pdf_url', models.URLField(blank=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worked_solutions', to='igcse_catalog.igcsegeneratedset')),
            ],
        ),
        migrations.AddIndex(
            model_name='igcsegeneratedset',
            index=models.Index(fields=['chapter', 'is_published', '-generated_at'], name='igcse_catal_chapter_721bb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='igcsechapter',
            constraint=models.UniqueConstraint(fields=('subject', 'slug'), name='igcse_catalog_chapter_subject_slug_uniq'),
        ),
    ]
