# Generated by Django 5.2.7 on 2026-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igcse_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='igcsegeneratedset',
            name='is_latest_published',
            field=models.BooleanField(default=False, help_text='When true, this set is the canonical published release for its chapter.'),
        ),
        migrations.AddField(
            model_name='igcsegeneratedset',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Monotonic version per chapter when the pipeline re-generates content.'),
        ),
        migrations.AddIndex(
            model_name='igcsegeneratedset',
            index=models.Index(fields=['chapter', 'is_latest_published'], name='igcse_catal_chapter_4747c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='igcsegeneratedset',
            constraint=models.UniqueConstraint(condition=models.Q(('pipeline_bundle_id__gt', '')), fields=('chapter', 'pipeline_bundle_id'), name='igcse_catalog_chapter_bundle_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igcsegeneratedset',
            constraint=models.UniqueConstraint(fields=('chapter', 'version'), name='igcse_catalog_chapter_version_uniq'),
        ),
    ]
