# Generated by Django 5.2.7 on 2026-05-02 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userprofile_student_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedNormalizedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('exam_type', models.CharField(choices=[('WAEC', 'WAEC'), ('JAMB', 'JAMB')], max_length=8)),
                ('subject', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField(default=0)),
                ('external_id', models.CharField(max_length=128)),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'exam_type', 'subject', 'year'], name='learning_ca_provide_c13dd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='IgcsEpubBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=120)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('epub_url', models.URLField(blank=True)),
                ('epub_file', models.FileField(blank=True, upload_to='igcse/epubs/')),
                ('toc_json', models.JSONField(blank=True, default=list)),
                ('extra_metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null = available to all organizations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='igcse_epub_books', to='users.organization')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='IgcsBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('start_cfi', models.CharField(blank=True, max_length=512)),
                ('end_cfi', models.CharField(blank=True, max_length=512)),
                ('chapter_href', models.CharField(blank=True, max_length=512)),
                ('excerpt', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igcse_bookmarks', to='users.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igcse_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='learning.igcsepubbook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IgcsHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(default='#FFD54F', max_length=32)),
                ('start_cfi', models.CharField(blank=True, max_length=512)),
                ('end_cfi', models.CharField(blank=True, max_length=512)),
                ('chapter_href', models.CharField(blank=True, max_length=512)),
                ('excerpt', models.CharField(blank=True, max_length=512)),
                ('fallback_note', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='learning.igcsepubbook')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igcse_highlights', to='users.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igcse_highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IgcsNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('start_cfi', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.igcsepubbook')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igcse_notes', to='users.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igcse_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('WAEC', 'WAEC'), ('JAMB', 'JAMB')], max_length=8)),
                ('subject', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('score_percent', models.FloatField(default=0.0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('answered_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='users.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=128)),
                ('selected_option_id', models.CharField(blank=True, max_length=64)),
                ('correct_option_id', models.CharField(blank=True, max_length=64)),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('time_spent_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning.practicesession')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCacheBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('exam_type', models.CharField(choices=[('WAEC', 'WAEC'), ('JAMB', 'JAMB')], max_length=8)),
                ('subject', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField(default=0)),
                ('batch_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('questions_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'exam_type', 'subject', 'year'], name='learning_qu_provide_479793_idx')],
            },
        ),
        migrations.CreateModel(
            name='IgcsUserReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fraction', models.FloatField(default=0.0, help_text='0..1 overall progress.')),
                ('start_cfi', models.CharField(blank=True, max_length=512)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_readings', to='learning.igcsepubbook')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igcse_readings', to='users.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igcse_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_read_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
