# Generated by Django 5.2.7 on 2026-06-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_igcsepubbook_import_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='igcsepubbook',
            name='content_source',
            field=models.CharField(blank=True, help_text='Attribution or source URL for the content (e.g. Project Gutenberg, publisher name).', max_length=512),
        ),
        migrations.AddField(
            model_name='igcsepubbook',
            name='license_type',
            field=models.CharField(choices=[('public_domain', 'Public Domain'), ('licensed', 'Licensed (permission granted)'), ('restricted', 'Restricted (do not distribute)'), ('unknown', 'Unknown — needs review')], default='unknown', help_text='Type of license that permits distribution of this content.', max_length=20),
        ),
        migrations.AddField(
            model_name='igcsepubbook',
            name='rights_notes',
            field=models.TextField(blank=True, help_text='Admin notes on licensing, permissions, or review history.'),
        ),
        migrations.AddField(
            model_name='igcsepubbook',
            name='rights_status',
            field=models.CharField(choices=[('approved', 'Approved for distribution'), ('draft', 'Draft — not yet approved'), ('expired', 'License expired'), ('restricted', 'Restricted — internal use only'), ('unknown', 'Unknown — needs review')], default='draft', help_text="Current approval/publishing state. Only 'approved' content should be production-visible.", max_length=20),
        ),
        migrations.AlterField(
            model_name='igcsepubbook',
            name='epub_file',
            field=models.FileField(blank=True, help_text='Upload an .epub, or leave empty and use Import source URL below.', upload_to='igcse/epubs/'),
        ),
        migrations.AlterField(
            model_name='igcsepubbook',
            name='epub_url',
            field=models.URLField(blank=True, help_text='Direct HTTPS link to an .epub file (e.g. Gutenberg cache URL).'),
        ),
        migrations.AlterField(
            model_name='igcsepubbook',
            name='import_source_url',
            field=models.URLField(blank=True, help_text='epub.pub / readanybook.com page or remote EPUB archive URL — downloaded on save via epub_downloader (see learning admin help).'),
        ),
    ]
