# Generated by Django 5.2.7 on 2026-10-05 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_protected_pdf_assets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.BinaryField()),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='protectedpdfasset',
            name='audience_classes',
            field=models.JSONField(blank=True, default=list, help_text="School resources only: list of class names (e.g. ['SS2A']) that may see this file. Empty = every student in the organization."),
        ),
        migrations.AddField(
            model_name='protectedpdfasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_protected_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PdfAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('pen', 'Pen'), ('highlight', 'Highlighter'), ('note', 'Sticky note')], max_length=16)),
                ('color', models.CharField(default='#FFEB3B', max_length=16)),
                ('width', models.FloatField(default=0.004, help_text='Stroke width as a fraction of page width.')),
                ('points', models.JSONField(blank=True, default=list, help_text='Pen/highlight: [[x, y], ...] normalised 0..1. Note: [[x, y]] anchor.')),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='learning.protectedpdfasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page', 'created_at'],
                'indexes': [models.Index(fields=['user', 'asset'], name='learning_pdfann_user_asset')],
            },
        ),
    ]
