"""
Django settings for smartshelfbackend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-66%0=8@hdhy%yj)@9g+hh(k$xwhp=%#&a)r*)thjn-p15e+5hr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # In production, specify actual hosts

# Required for Django admin login over HTTPS (Render, etc.).
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "https://smartshelf-api.onrender.com",
    ).split(",")
    if origin.strip()
]

# Render terminates TLS at the load balancer.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'users',
    'auth',
    'quotes',
    'pdf_proxy',
    'learning',
    'igcse_catalog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'smartshelfbackend.dev_cors_middleware.DevCorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.CurrentOrganizationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartshelfbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartshelfbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'smartshelf'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Protected PDF assets ──────────────────────────────────────────────────
# Raw protected PDFs are stored OUTSIDE MEDIA_ROOT so the dev static-media
# handler (and any public web server config) never serves them directly.
# Access is only ever granted through signed, short-lived download tokens.
PROTECTED_MEDIA_ROOT = os.getenv(
    'PROTECTED_MEDIA_ROOT', str(BASE_DIR / 'protected_media')
)
# Lifetime (seconds) of a signed download token returned by authorize-download.
PROTECTED_DOWNLOAD_TOKEN_MAX_AGE = int(
    os.getenv('PROTECTED_DOWNLOAD_TOKEN_MAX_AGE', '300')
)
# How long an already-downloaded copy may be opened offline before the app
# must re-authorize with the backend (enables rights revocation over time).
PROTECTED_OFFLINE_ACCESS_DAYS = int(
    os.getenv('PROTECTED_OFFLINE_ACCESS_DAYS', '30')
)

# Repo-bundled IGCSE EPUBs (see SmartShelfRepo/bundled-igcse/)
BUNDLED_IGCSE_EPUB_DIR = os.getenv(
    'BUNDLED_IGCSE_EPUB_DIR',
    str(BASE_DIR.parent.parent / 'bundled-igcse' / 'epubs'),
)
BUNDLED_IGCSE_MANIFEST = os.getenv(
    'BUNDLED_IGCSE_MANIFEST',
    str(BASE_DIR.parent.parent / 'bundled-igcse' / 'manifest.json'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.UserProfile'

# Dev only: omit Bearer token for this many minutes after Django starts (requires restart after change).
# See users.auth_bypass / users.authentication.DevBypassAuthentication
AUTH_FREE_FOR_MINUTES = int(os.getenv('AUTH_FREE_FOR_MINUTES', '0'))
AUTH_BYPASS_USER_ID = os.getenv('AUTH_BYPASS_USER_ID', '').strip()

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.DevBypassAuthentication',
        'users.authentication.BearerTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/day',
        'login': os.getenv('AUTH_RATE_LIMIT_LOGIN', '10/min'),
        'register': os.getenv('AUTH_RATE_LIMIT_REGISTER', '5/min'),
        'password_reset': os.getenv('AUTH_RATE_LIMIT_PASSWORD_RESET', '5/min'),
    },
}

from users.auth_bypass import configure_deadline_minutes  # noqa: E402

configure_deadline_minutes(AUTH_FREE_FOR_MINUTES)

# External quotes service (used by /api/quotes/random/)
QUOTES_API_URL = os.getenv('QUOTES_API_URL', 'http://localhost:8080/')

# ------------------------------------------------------------------------------
# Learning / practice integrations (see learning/question_service.py)
# ------------------------------------------------------------------------------
# ALOC Questions API: https://github.com/Seunope/aloc-endpoints — hosted example https://questions.aloc.com.ng/api/v2/
ALOC_API_BASE_URL = os.getenv('ALOC_API_BASE_URL', 'https://questions.aloc.com.ng/api/v2').rstrip('/')
ALOC_ACCESS_TOKEN = os.getenv('ALOC_ACCESS_TOKEN', '')
ALOC_REQUEST_TIMEOUT = float(os.getenv('ALOC_REQUEST_TIMEOUT', '15'))
ALOC_EXAM_TYPE_WAEC = os.getenv('ALOC_EXAM_TYPE_WAEC', 'wassce')
ALOC_EXAM_TYPE_JAMB = os.getenv('ALOC_EXAM_TYPE_JAMB', 'utme')

# Practice shelf uses ALOC for WAEC/JAMB only (see learning/question_service.py).
LEARNING_QUESTION_PROVIDER = os.getenv('LEARNING_QUESTION_PROVIDER', 'aloc')

QUESTION_CACHE_TTL_SECONDS = int(os.getenv('QUESTION_CACHE_TTL_SECONDS', '3600'))

# OpenAI — server-side proxy for practice answer explanations (mobile calls /api/v1/practice/explain/)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_EXPLAIN_MODEL = os.getenv('OPENAI_EXPLAIN_MODEL', 'gpt-4o-mini')
OPENAI_REQUEST_TIMEOUT = float(os.getenv('OPENAI_REQUEST_TIMEOUT', '30'))

# Optional JSON overrides for subject/year lists: '["chemistry","english"]'
PRACTICE_SUBJECTS_WAEC_JSON = os.getenv('PRACTICE_SUBJECTS_WAEC_JSON', '')
PRACTICE_SUBJECTS_JAMB_JSON = os.getenv('PRACTICE_SUBJECTS_JAMB_JSON', '')
PRACTICE_YEARS_JSON = os.getenv('PRACTICE_YEARS_JSON', '')

# ── Compliance / cross-border data disclosure ─────────────────────────────
# These values are returned by /api/v1/auth/policy-info/ and embedded in
# privacy disclosures served to users.
DATA_STORAGE_COUNTRY = os.getenv('DATA_STORAGE_COUNTRY', 'Nigeria')
DATA_STORAGE_REGION = os.getenv('DATA_STORAGE_REGION', 'West Africa')
PRIVACY_CONTACT_EMAIL = os.getenv('PRIVACY_CONTACT_EMAIL', 'privacy@smartshelf.ng')
# Jurisdiction flags — set to 'true' to enable jurisdiction-specific disclosures.
COMPLIANCE_NDPA = os.getenv('COMPLIANCE_NDPA', 'true').lower() == 'true'   # Nigeria NDPA
COMPLIANCE_COPPA = os.getenv('COMPLIANCE_COPPA', 'true').lower() == 'true'  # US COPPA
COMPLIANCE_PIPEDA = os.getenv('COMPLIANCE_PIPEDA', 'true').lower() == 'true'  # Canada PIPEDA

# Email settings (used by password reset flow).
# Default writes emails to console in local/dev unless overridden by env.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@smartshelf.app')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'auth': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
