# Generated by Django 5.2.7 on 2026-10-05 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0005_school_resources_pdf_annotations'),
        ('users', '0012_school_admin_join_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('practice', 'Past-question practice (WAEC/JAMB)'), ('reading', 'Reading'), ('questions', 'Teacher-written questions')], max_length=16)),
                ('target_class', models.CharField(blank=True, help_text='Class the assignment was set for, if any.', max_length=120)),
                ('exam_type', models.CharField(blank=True, max_length=10)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('question_count', models.PositiveSmallIntegerField(default=10)),
                ('resource_pages', models.CharField(blank=True, help_text="e.g. 'Chapter 3, pages 40-52'.", max_length=120)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.organization')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='learning.protectedpdfasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('mcq', 'Multiple choice'), ('short', 'Short answer'), ('theory', 'Theory / worked solution')], max_length=10)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(blank=True, default=list, help_text="Multiple choice only: [{'id': 'A', 'label': '...'}].")),
                ('correct_option_id', models.CharField(blank=True, max_length=16)),
                ('marking_guide', models.TextField(blank=True, help_text='Model answer / marking scheme. Shown to students after grading.')),
                ('max_marks', models.PositiveSmallIntegerField(default=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classroom.assignment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Not started'), ('submitted', 'Submitted, awaiting marking'), ('graded', 'Marked')], default='assigned', max_length=12)),
                ('response_text', models.TextField(blank=True, help_text="Reading assignments: the student's summary or reflection.")),
                ('awarded_marks', models.FloatField(blank=True, null=True)),
                ('score_percent', models.FloatField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classroom.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('practice_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning.practicesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assignment', 'student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option_id', models.CharField(blank=True, max_length=16)),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('awarded_marks', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.assignmentquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.assignmentsubmission')),
            ],
            options={
                'ordering': ['question__order'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(related_name='assignments_received', through='classroom.AssignmentSubmission', through_fields=('assignment', 'student'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='classroom_unique_submission'),
        ),
        migrations.AddConstraint(
            model_name='assignmentanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='classroom_unique_answer'),
        ),
    ]
